// This file is auto-generated by @hey-api/openapi-ts

/**
 * CheckStatus
 */
export type CheckStatus = 'pending' | 'success' | 'failed' | 'changed';

/**
 * CheckTrigger
 */
export type CheckTrigger = {
    /**
     * Website Ids
     * Specific website IDs to check, or None for all active websites
     */
    website_ids?: Array<string> | null;
};

/**
 * DashboardResponse
 */
export type DashboardResponse = {
    stats: WebsiteStats;
    /**
     * Recent Changes
     */
    recent_changes: Array<WebsiteCheckResponse>;
    /**
     * Failing Websites
     */
    failing_websites: Array<WebsiteResponse>;
};

/**
 * ExampleRequest
 */
export type ExampleRequest = {
    /**
     * Name
     * The name to be processed
     */
    name: string;
    /**
     * Age
     * The age of the person, must be non-negative
     */
    age?: number | null;
};

/**
 * ExampleResponse
 */
export type ExampleResponse = {
    /**
     * Message
     * The response message
     */
    message: string;
    /**
     * Claims
     * The claims associated with the response
     */
    claims: {
        [key: string]: unknown;
    };
    /**
     * Test Value
     * A test integer value
     */
    test_value?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NotificationChannel
 */
export type NotificationChannel = 'email' | 'telegram';

/**
 * NotificationSettingsResponse
 */
export type NotificationSettingsResponse = {
    /**
     * Email Address
     */
    email_address?: string | null;
    /**
     * Email Enabled
     */
    email_enabled?: boolean;
    /**
     * Telegram Chat Id
     */
    telegram_chat_id?: string | null;
    /**
     * Telegram Enabled
     */
    telegram_enabled?: boolean;
    /**
     * Telegram Bot Token
     */
    telegram_bot_token?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * NotificationSettingsUpdate
 */
export type NotificationSettingsUpdate = {
    /**
     * Email Address
     */
    email_address?: string | null;
    /**
     * Email Enabled
     */
    email_enabled?: boolean | null;
    /**
     * Telegram Chat Id
     */
    telegram_chat_id?: string | null;
    /**
     * Telegram Enabled
     */
    telegram_enabled?: boolean | null;
    /**
     * Telegram Bot Token
     */
    telegram_bot_token?: string | null;
};

/**
 * UserProfile
 */
export type UserProfile = {
    /**
     * Sub
     */
    sub: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Picture
     */
    picture?: string | null;
    /**
     * Bio
     */
    bio?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean | null;
};

/**
 * UserProfileUpdate
 */
export type UserProfileUpdate = {
    /**
     * Name
     * User's display name
     */
    name?: string | null;
    /**
     * Nickname
     * User's nickname
     */
    nickname?: string | null;
    /**
     * Picture
     * URL to user's profile picture
     */
    picture?: string | null;
    /**
     * Bio
     * User's biography
     */
    bio?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WebsiteCheckListResponse
 */
export type WebsiteCheckListResponse = {
    /**
     * Items
     */
    items: Array<WebsiteCheckResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * WebsiteCheckResponse
 */
export type WebsiteCheckResponse = {
    status: CheckStatus;
    /**
     * Content Hash
     */
    content_hash?: string | null;
    /**
     * Screenshot Path
     */
    screenshot_path?: string | null;
    /**
     * Changes Detected
     */
    changes_detected?: boolean;
    /**
     * Change Summary
     */
    change_summary?: string | null;
    /**
     * Response Time Ms
     */
    response_time_ms?: number | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Website Id
     */
    website_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * WebsiteCreate
 */
export type WebsiteCreate = {
    /**
     * Name
     * Website display name
     */
    name: string;
    /**
     * Url
     * Website URL to monitor
     */
    url: string;
    /**
     * Check Interval Minutes
     * Check interval in minutes (5 min to 1 week)
     */
    check_interval_minutes?: number;
    /**
     * Is Active
     * Whether monitoring is active
     */
    is_active?: boolean;
    /**
     * Ignore Selectors
     * CSS selectors to ignore in change detection
     */
    ignore_selectors?: Array<string> | null;
    /**
     * Email Notifications
     * Send email notifications
     */
    email_notifications?: boolean;
    /**
     * Telegram Notifications
     * Send Telegram notifications
     */
    telegram_notifications?: boolean;
};

/**
 * WebsiteListResponse
 */
export type WebsiteListResponse = {
    /**
     * Items
     */
    items: Array<WebsiteResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * WebsiteResponse
 */
export type WebsiteResponse = {
    /**
     * Name
     * Website display name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    /**
     * Check Interval Minutes
     * Check interval in minutes (5 min to 1 week)
     */
    check_interval_minutes?: number;
    /**
     * Is Active
     * Whether monitoring is active
     */
    is_active?: boolean;
    /**
     * Ignore Selectors
     * CSS selectors to ignore in change detection
     */
    ignore_selectors?: Array<string> | null;
    /**
     * Email Notifications
     * Send email notifications
     */
    email_notifications?: boolean;
    /**
     * Telegram Notifications
     * Send Telegram notifications
     */
    telegram_notifications?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WebsiteStats
 */
export type WebsiteStats = {
    /**
     * Total Websites
     */
    total_websites: number;
    /**
     * Active Websites
     */
    active_websites: number;
    /**
     * Total Checks
     */
    total_checks: number;
    /**
     * Checks Last 24H
     */
    checks_last_24h: number;
    /**
     * Websites With Changes
     */
    websites_with_changes: number;
    /**
     * Avg Response Time Ms
     */
    avg_response_time_ms: number | null;
};

/**
 * WebsiteUpdate
 */
export type WebsiteUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Check Interval Minutes
     */
    check_interval_minutes?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Ignore Selectors
     */
    ignore_selectors?: Array<string> | null;
    /**
     * Email Notifications
     */
    email_notifications?: boolean | null;
    /**
     * Telegram Notifications
     */
    telegram_notifications?: boolean | null;
};

/**
 * WebsiteWithChecks
 */
export type WebsiteWithChecks = {
    /**
     * Name
     * Website display name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    /**
     * Check Interval Minutes
     * Check interval in minutes (5 min to 1 week)
     */
    check_interval_minutes?: number;
    /**
     * Is Active
     * Whether monitoring is active
     */
    is_active?: boolean;
    /**
     * Ignore Selectors
     * CSS selectors to ignore in change detection
     */
    ignore_selectors?: Array<string> | null;
    /**
     * Email Notifications
     * Send email notifications
     */
    email_notifications?: boolean;
    /**
     * Telegram Notifications
     * Send Telegram notifications
     */
    telegram_notifications?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Recent Checks
     */
    recent_checks?: Array<WebsiteCheckResponse>;
    /**
     * Last Check At
     */
    last_check_at?: string | null;
    /**
     * Last Change At
     */
    last_change_at?: string | null;
};

export type HttpException = {
    detail: string;
};

export type TestExampleEndpointData = {
    body: ExampleRequest;
    path?: never;
    query?: never;
    url: '/api/v1/test/';
};

export type TestExampleEndpointErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestExampleEndpointError = TestExampleEndpointErrors[keyof TestExampleEndpointErrors];

export type TestExampleEndpointResponses = {
    /**
     * Successful Response
     */
    200: ExampleResponse;
};

export type TestExampleEndpointResponse = TestExampleEndpointResponses[keyof TestExampleEndpointResponses];

export type UsersGetCurrentUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersGetCurrentUserProfileErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
};

export type UsersGetCurrentUserProfileError = UsersGetCurrentUserProfileErrors[keyof UsersGetCurrentUserProfileErrors];

export type UsersGetCurrentUserProfileResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type UsersGetCurrentUserProfileResponse = UsersGetCurrentUserProfileResponses[keyof UsersGetCurrentUserProfileResponses];

export type UsersUpdateUserProfileData = {
    body: UserProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserProfileErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserProfileError = UsersUpdateUserProfileErrors[keyof UsersUpdateUserProfileErrors];

export type UsersUpdateUserProfileResponses = {
    /**
     * Successful Response
     */
    200: UserProfile;
};

export type UsersUpdateUserProfileResponse = UsersUpdateUserProfileResponses[keyof UsersUpdateUserProfileResponses];

export type UsersGetAuth0ManagementUrlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/auth0-management-url';
};

export type UsersGetAuth0ManagementUrlErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
};

export type UsersGetAuth0ManagementUrlError = UsersGetAuth0ManagementUrlErrors[keyof UsersGetAuth0ManagementUrlErrors];

export type UsersGetAuth0ManagementUrlResponses = {
    /**
     * Response Users-Get Auth0 Management Url
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type UsersGetAuth0ManagementUrlResponse = UsersGetAuth0ManagementUrlResponses[keyof UsersGetAuth0ManagementUrlResponses];

export type WebsitesGetWebsitesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/websites/';
};

export type WebsitesGetWebsitesErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesGetWebsitesError = WebsitesGetWebsitesErrors[keyof WebsitesGetWebsitesErrors];

export type WebsitesGetWebsitesResponses = {
    /**
     * Successful Response
     */
    200: WebsiteListResponse;
};

export type WebsitesGetWebsitesResponse = WebsitesGetWebsitesResponses[keyof WebsitesGetWebsitesResponses];

export type WebsitesCreateWebsiteData = {
    body: WebsiteCreate;
    path?: never;
    query?: never;
    url: '/api/v1/websites/';
};

export type WebsitesCreateWebsiteErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesCreateWebsiteError = WebsitesCreateWebsiteErrors[keyof WebsitesCreateWebsiteErrors];

export type WebsitesCreateWebsiteResponses = {
    /**
     * Successful Response
     */
    201: WebsiteResponse;
};

export type WebsitesCreateWebsiteResponse = WebsitesCreateWebsiteResponses[keyof WebsitesCreateWebsiteResponses];

export type WebsitesDeleteWebsiteData = {
    body?: never;
    path: {
        /**
         * Website Id
         */
        website_id: string;
    };
    query?: never;
    url: '/api/v1/websites/{website_id}';
};

export type WebsitesDeleteWebsiteErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesDeleteWebsiteError = WebsitesDeleteWebsiteErrors[keyof WebsitesDeleteWebsiteErrors];

export type WebsitesDeleteWebsiteResponses = {
    /**
     * Response Websites-Delete Website
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type WebsitesDeleteWebsiteResponse = WebsitesDeleteWebsiteResponses[keyof WebsitesDeleteWebsiteResponses];

export type WebsitesGetWebsiteData = {
    body?: never;
    path: {
        /**
         * Website Id
         */
        website_id: string;
    };
    query?: {
        /**
         * Include Checks
         * Number of recent checks to include
         */
        include_checks?: number;
    };
    url: '/api/v1/websites/{website_id}';
};

export type WebsitesGetWebsiteErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesGetWebsiteError = WebsitesGetWebsiteErrors[keyof WebsitesGetWebsiteErrors];

export type WebsitesGetWebsiteResponses = {
    /**
     * Successful Response
     */
    200: WebsiteWithChecks;
};

export type WebsitesGetWebsiteResponse = WebsitesGetWebsiteResponses[keyof WebsitesGetWebsiteResponses];

export type WebsitesUpdateWebsiteData = {
    body: WebsiteUpdate;
    path: {
        /**
         * Website Id
         */
        website_id: string;
    };
    query?: never;
    url: '/api/v1/websites/{website_id}';
};

export type WebsitesUpdateWebsiteErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesUpdateWebsiteError = WebsitesUpdateWebsiteErrors[keyof WebsitesUpdateWebsiteErrors];

export type WebsitesUpdateWebsiteResponses = {
    /**
     * Successful Response
     */
    200: WebsiteResponse;
};

export type WebsitesUpdateWebsiteResponse = WebsitesUpdateWebsiteResponses[keyof WebsitesUpdateWebsiteResponses];

export type WebsitesGetWebsiteChecksData = {
    body?: never;
    path: {
        /**
         * Website Id
         */
        website_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/websites/{website_id}/checks';
};

export type WebsitesGetWebsiteChecksErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesGetWebsiteChecksError = WebsitesGetWebsiteChecksErrors[keyof WebsitesGetWebsiteChecksErrors];

export type WebsitesGetWebsiteChecksResponses = {
    /**
     * Successful Response
     */
    200: WebsiteCheckListResponse;
};

export type WebsitesGetWebsiteChecksResponse = WebsitesGetWebsiteChecksResponses[keyof WebsitesGetWebsiteChecksResponses];

export type WebsitesTriggerWebsiteCheckData = {
    body: CheckTrigger;
    path?: never;
    query?: never;
    url: '/api/v1/websites/check';
};

export type WebsitesTriggerWebsiteCheckErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesTriggerWebsiteCheckError = WebsitesTriggerWebsiteCheckErrors[keyof WebsitesTriggerWebsiteCheckErrors];

export type WebsitesTriggerWebsiteCheckResponses = {
    /**
     * Response Websites-Trigger Website Check
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type WebsitesTriggerWebsiteCheckResponse = WebsitesTriggerWebsiteCheckResponses[keyof WebsitesTriggerWebsiteCheckResponses];

export type WebsitesGetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/websites/dashboard/stats';
};

export type WebsitesGetDashboardStatsErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
};

export type WebsitesGetDashboardStatsError = WebsitesGetDashboardStatsErrors[keyof WebsitesGetDashboardStatsErrors];

export type WebsitesGetDashboardStatsResponses = {
    /**
     * Successful Response
     */
    200: DashboardResponse;
};

export type WebsitesGetDashboardStatsResponse = WebsitesGetDashboardStatsResponses[keyof WebsitesGetDashboardStatsResponses];

export type WebsitesGetNotificationSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/websites/settings/notifications';
};

export type WebsitesGetNotificationSettingsErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
};

export type WebsitesGetNotificationSettingsError = WebsitesGetNotificationSettingsErrors[keyof WebsitesGetNotificationSettingsErrors];

export type WebsitesGetNotificationSettingsResponses = {
    /**
     * Successful Response
     */
    200: NotificationSettingsResponse;
};

export type WebsitesGetNotificationSettingsResponse = WebsitesGetNotificationSettingsResponses[keyof WebsitesGetNotificationSettingsResponses];

export type WebsitesUpdateNotificationSettingsData = {
    body: NotificationSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/websites/settings/notifications';
};

export type WebsitesUpdateNotificationSettingsErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesUpdateNotificationSettingsError = WebsitesUpdateNotificationSettingsErrors[keyof WebsitesUpdateNotificationSettingsErrors];

export type WebsitesUpdateNotificationSettingsResponses = {
    /**
     * Successful Response
     */
    200: NotificationSettingsResponse;
};

export type WebsitesUpdateNotificationSettingsResponse = WebsitesUpdateNotificationSettingsResponses[keyof WebsitesUpdateNotificationSettingsResponses];

export type WebsitesTestNotificationData = {
    body?: never;
    path?: never;
    query: {
        channel: NotificationChannel;
    };
    url: '/api/v1/websites/settings/notifications/test';
};

export type WebsitesTestNotificationErrors = {
    /**
     * Bad Request
     */
    400: HttpException;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebsitesTestNotificationError = WebsitesTestNotificationErrors[keyof WebsitesTestNotificationErrors];

export type WebsitesTestNotificationResponses = {
    /**
     * Response Websites-Test Notification
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type WebsitesTestNotificationResponse = WebsitesTestNotificationResponses[keyof WebsitesTestNotificationResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};