"""Add website monitoring models

Revision ID: b3ffaa1a3f4c
Revises:
Create Date: 2025-08-15 16:20:19.513760

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "b3ffaa1a3f4c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notification_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "telegram_chat_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("telegram_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "telegram_bot_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_notification_settings_id"),
        "user_notification_settings",
        ["id"],
        unique=False,
    )
    op.create_table(
        "websites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("check_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "ignore_selectors", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("telegram_notifications", sa.Boolean(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_websites_id"), "websites", ["id"], unique=False)
    op.create_table(
        "website_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("website_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "FAILED", "CHANGED", name="checkstatus"),
            nullable=False,
        ),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("screenshot_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("changes_detected", sa.Boolean(), nullable=False),
        sa.Column("change_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_website_checks_id"), "website_checks", ["id"], unique=False
    )
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("website_check_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "TELEGRAM", name="notificationchannel"),
            nullable=False,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["website_check_id"],
            ["website_checks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_logs_id"), "notification_logs", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_logs_id"), table_name="notification_logs")
    op.drop_table("notification_logs")
    op.drop_index(op.f("ix_website_checks_id"), table_name="website_checks")
    op.drop_table("website_checks")
    op.drop_index(op.f("ix_websites_id"), table_name="websites")
    op.drop_table("websites")
    op.drop_index(
        op.f("ix_user_notification_settings_id"),
        table_name="user_notification_settings",
    )
    op.drop_table("user_notification_settings")
    # ### end Alembic commands ###
